version: '3.4'

services:

  pub-microservice:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   ports:
      - "60001:50001"

  pub-microservice-dapr:
    command: ["./daprd",
      "-app-id", "publisher",
      "-app-port", "80",
      "-components-path", "/components"      
      ]
    volumes:
      - "./dapr/components/:/components"

  bindings-microservice:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   ports:
      - "60002:50001"

  bindings-microservice-dapr:
    command: ["./daprd",
      "-app-id", "bindings",
      "-app-port", "80",
      "-components-path", "/components"      
      ]
    volumes:
      - "./dapr/components/:/components"