apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
 name: bindings
spec:
 type: bindings.azure.eventhubs
 version: v1  
 metadata:
 - name: connectionString
   secretKeyRef:
     name: bindings:ehConnectionString
     key: bindings:ehConnectionString
  - name: consumerGroup
    value: "consumergroupbinding"     
 - name: storageAccountName
   secretKeyRef:
     name: common:storageAccountName
     key: common:storageAccountName
 - name: storageAccountKey
   secretKeyRef:
     name: common:storageAccountKey
     key: common:storageAccountKey    
 - name: storageContainerName
   secretKeyRef:
     name: common:storageContainerName
     key: common:storageContainerName        
auth:
 secretStore: secret-local-store